df <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
df1 <- df[(df$Date=="1/2/2007" | df$Date=="2/2/2007"),]
df1$dtime <- paste(df1$Date, df1$Time)
df1$dtime <- strptime(df1$dtime, "%d/%m/%Y %H:%M:%S")
df1$Global_active_power <- as.numeric(levels(df1[,3])[df1[,3]])
df1$Voltage <- as.numeric(levels(df1[,5])[df1[,5]])
df1$Sub_metering_1 <- as.numeric(levels(df1[,7])[df1[,7]])
df1$Sub_metering_2 <- as.numeric(levels(df1[,8])[df1[,8]])
df1$Global_reactive_power <- as.numeric(levels(df1[,4])[df1[,4]])
png(file="plot4.png")
par(mfrow = c(2,2))
plot(df1$dtime, df1$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(df1$dtime, df1$Voltage, type="l", xlab="datetime", ylab="Voltage")
with(df1, plot(dtime,Sub_metering_1,type="l",xlab="",ylab="Energy sub metering"))
with(df1, lines(dtime,Sub_metering_2,col="Red"))
with(df1, lines(dtime,Sub_metering_3,col="blue"))
legend("topright",pch="_",bty="n",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(df1$dtime, df1$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
